name: assignment
on: issue_comment

permissions:
  issues: write
  pull-requests: write

jobs:
  ghapi-exercise:
    if: (github.event.issue.pull_request != null) && contains(github.event.comment.body, '/wandb')
    runs-on: ubuntu-latest
    steps:        
    - name: install dependencies
      run: pip install ghapi wandb

    - name: see payload # this step is for debugging purposes only, so you can see the payload. 
      run: echo "PAYLOAD:\n${PAYLOAD}\n"
      env:
        PAYLOAD: ${{ toJSON(github.event) }}
      
    - name: parse run-ID
      shell: python
      run: |
        import os
        from ghapi.core import GhApi
        owner,repo = os.environ['REPO'].split('/')
        run_id = os.environ['COMMENT'].split( )[1]
        api = GhApi(owner=owner, repo=repo)
        print(run_id)
      env:
        NUMBER: ${{ github.event.issue.number }} 
        COMMENT: ${{ github.event.comment.body }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
